# Generated by Django 3.2.6 on 2021-08-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
